#!/usr/bin/env bash
set -Eeuo pipefail

# User-scoped installer. It never uses sudo and never writes outside INSTALL_DIR.

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SOURCE_DIR=$SCRIPT_DIR/..
INSTALL_DIR=${UNIVERSAL_DASHBOARD_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/universal-dashboard-agent}
SKIP_BROWSER=0
SKIP_BUILD=0
NO_COPY=0

usage() {
  sed -n '2,5p' "$0"
  printf '\nUsage: %s [--source DIR] [--install-dir DIR] [--skip-browser] [--skip-build] [--no-copy]\n' "$0"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source) SOURCE_DIR=$(CDPATH= cd -- "$2" && pwd); shift 2 ;;
    --install-dir) INSTALL_DIR=$(CDPATH= cd -- "$(dirname -- "$2")" && pwd)/$(basename -- "$2"); shift 2 ;;
    --skip-browser) SKIP_BROWSER=1; shift ;;
    --skip-build) SKIP_BUILD=1; shift ;;
    --no-copy) NO_COPY=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ ! -f "$SOURCE_DIR/pyproject.toml" ]]; then
  printf 'Source directory does not contain pyproject.toml: %s\n' "$SOURCE_DIR" >&2
  exit 1
fi
PYTHON=${PYTHON:-python3}
NODE=${NODE:-node}
command -v "$PYTHON" >/dev/null 2>&1 || { printf 'Python 3.11+ is required; install it for your user account.\n' >&2; exit 1; }
command -v "$NODE" >/dev/null 2>&1 || { printf 'Node.js 20.9+ is required; install it for your user account.\n' >&2; exit 1; }
"$PYTHON" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else "Python 3.11+ is required")'
"$NODE" -e 'const [major,minor]=process.versions.node.split(".").map(Number); if (major < 20 || (major === 20 && minor < 9)) process.exit(1)' || {
  printf 'Node.js 20.9+ is required (found %s).\n' "$($NODE --version)" >&2; exit 1;
}

mkdir -p "$INSTALL_DIR"
if [[ "$NO_COPY" -eq 0 && "$SOURCE_DIR" != "$INSTALL_DIR" ]]; then
  tar -C "$SOURCE_DIR" --exclude=.git --exclude=.venv --exclude=.hermes-runtime --exclude=.playwright \
    --exclude=private_source_dashboard.xlsx --exclude=reports --exclude=data -cf - . | tar -C "$INSTALL_DIR" -xf -
fi
VENV="$INSTALL_DIR/.venv"
HERMES_ENV="$INSTALL_DIR/.hermes-runtime"
PLAYWRIGHT_DIR="$INSTALL_DIR/.playwright"
"$PYTHON" -m venv "$VENV"
"$VENV/bin/python" -m pip install --upgrade pip
"$VENV/bin/python" -m pip install --upgrade "$INSTALL_DIR"
if [[ "$SKIP_BROWSER" -eq 0 ]]; then
  PLAYWRIGHT_BROWSERS_PATH="$PLAYWRIGHT_DIR" "$VENV/bin/python" -m playwright install chromium
fi
"$PYTHON" -m venv "$HERMES_ENV"
"$HERMES_ENV/bin/python" -m pip install --upgrade pip
"$HERMES_ENV/bin/python" -m pip install --upgrade 'hermes-agent==0.13.0'
if [[ "$SKIP_BUILD" -eq 0 ]]; then
  (cd "$INSTALL_DIR/dashboard/web" && npm ci && npm run build)
fi

mkdir -p "$INSTALL_DIR/bin" "$INSTALL_DIR/config"
umask 077
if [[ ! -f "$INSTALL_DIR/config/local.env" ]]; then
  cat >"$INSTALL_DIR/config/local.env" <<EOF
# Generated by install-linux.sh. Keep this file mode 600.
DASHBOARD_API_HOST=127.0.0.1
DASHBOARD_API_PORT=8000
DASHBOARD_WEB_HOST=127.0.0.1
DASHBOARD_WEB_PORT=3000
DASHBOARD_ALLOWED_ORIGINS=http://127.0.0.1:3000
DASHBOARD_ENFORCE_LOCAL_SECURITY=true
PLAYWRIGHT_BROWSERS_PATH=$PLAYWRIGHT_DIR
EOF
  chmod 600 "$INSTALL_DIR/config/local.env"
fi
cat >"$INSTALL_DIR/bin/dashboard-start" <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail
BASE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
set -a
. "$BASE_DIR/config/local.env"
set +a
export DASHBOARD_LOCAL_AUTH_TOKEN=$("$BASE_DIR/.venv/bin/python" -c 'import secrets; print(secrets.token_urlsafe(32))')
cd "$BASE_DIR"
trap 'kill 0' EXIT INT TERM
"$BASE_DIR/.venv/bin/python" -m uvicorn dashboard.api.main:app --host "${DASHBOARD_API_HOST:-127.0.0.1}" --port "${DASHBOARD_API_PORT:-8000}" &
(cd dashboard/web && npm run start -- -H "${DASHBOARD_WEB_HOST:-127.0.0.1}" -p "${DASHBOARD_WEB_PORT:-3000}") &
wait
EOF
chmod 700 "$INSTALL_DIR/bin/dashboard-start"
cat >"$INSTALL_DIR/bin/dashboard-first-run" <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail
BASE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
exec "$BASE_DIR/.venv/bin/python" -m automation.release.first_run --root "$BASE_DIR" --runtime "$BASE_DIR/.hermes-runtime" "$@"
EOF
chmod 700 "$INSTALL_DIR/bin/dashboard-first-run"
printf '\nInstalled Universal Dashboard Agent in %s\n' "$INSTALL_DIR"
printf 'Run diagnostics/provider setup: %s/bin/dashboard-first-run\n' "$INSTALL_DIR"
printf 'Start the loopback-only app: %s/bin/dashboard-start\n' "$INSTALL_DIR"
printf 'To uninstall, run scripts/uninstall-linux.sh --install-dir %s --yes from the source checkout.\n' "$INSTALL_DIR"
